from enum import Enum

from ww.locale import ZhTwEnum, _


class TemplateResonatorTableColumnEnum(str, Enum):
    RESONATOR_NAME: str = _(ZhTwEnum.RESONATOR_NAME)
    RESONATOR_CHAIN: str = _(ZhTwEnum.RESONATOR_CHAIN)
    RESONATOR_WEAPON_NAME: str = _(ZhTwEnum.RESONATOR_WEAPON_NAME)
    RESONATOR_WEAPON_RANK: str = _(ZhTwEnum.RESONATOR_WEAPON_RANK)
    RESONATOR_INHERENT_SKILL_1: bool = _(ZhTwEnum.RESONATOR_INHERENT_SKILL_1)
    RESONATOR_INHERENT_SKILL_2: bool = _(ZhTwEnum.RESONATOR_INHERENT_SKILL_2)
    RESONATOR_BASE_ATTR: str = _(ZhTwEnum.RESONATOR_BASE_ATTR)
    RESONATOR_SKILL_BONUS: str = _(ZhTwEnum.RESONATOR_SKILL_BONUS)
    RESONATOR_ECHO_1: str = _(ZhTwEnum.RESONATOR_ECHO_1)
    RESONATOR_ECHO_SONATA_1: str = _(ZhTwEnum.RESONATOR_ECHO_SONATA_1)
    RESONATOR_ECHO_SONATA_2: str = _(ZhTwEnum.RESONATOR_ECHO_SONATA_2)
    RESONATOR_ECHO_SONATA_3: str = _(ZhTwEnum.RESONATOR_ECHO_SONATA_3)
    RESONATOR_ECHO_SONATA_4: str = _(ZhTwEnum.RESONATOR_ECHO_SONATA_4)
    RESONATOR_ECHO_SONATA_5: str = _(ZhTwEnum.RESONATOR_ECHO_SONATA_5)
