from enum import Enum


class TemplateEnum(str, Enum):
    RESONATOR_NAME: str = "[角色]名稱"
    REAL_DMG_NO_CRIT: str = "[實戰]無暴擊"
    REAL_DMG_CRIT: str = "[實戰]暴擊"
    ACTION: str = "[實戰]操作"
    SKILL_ID: str = "[實戰]技能代稱"
    BONUS_TYPE: str = "[實戰]技能加成種類"
    BONUS_MAGNIFIER: str = "[額外]倍率"
    BONUS_AMPLIFIER: str = "[額外]加深"
    BONUS_ATK_P: str = "[額外]攻擊百分比"
    BONUS_ATK: str = "[額外]攻擊"
    BONUS_CRIT_RATE: str = "[額外]暴擊"
    BONUS_CRIT_DMG: str = "[額外]暴擊傷害"
    BONUS_ADDITION: str = "[額外]加成"
    BONUS_SKILL_DMG_ADDITION: str = "[額外]招式倍率"
    BONUS_IGNORE_DEF: str = "[額外]忽視防禦"
    BONUS_REDUCE_RES: str = "[額外]抗性降低"
    RESONATING_SPIN_CONCERTO_REGEN: str = "協奏能量"
    ACCUMULATED_RESONATING_SPIN_CONCERTO_REGEN: str = "累積協奏"
    TIME_START: str = "[實戰]起手秒數"
    TIME_END: str = "[實戰]結束秒數"
    CUMULATIVE_TIME: str = "[實戰]累積結束秒數"
    FRAME: str = "幀數"
